# Generated by Django 5.1.7 on 2025-03-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_clientfeedback_delete_contactform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientfeedback',
            name='service',
            field=models.CharField(max_length=256),
        ),
    ]
